### PR TITLE
fix: ecmaVersion 7 => 2017 to support async await

### PR DESCRIPTION
**Pull request by dead-horse**
https://github.com/MatAtBread/acorn-es7-plugin/blob/master/test/test-es5.js#L12

### CODE REVIEW

**Comment by dead-horse** [comment]
`ecmaVersion: 7` will throw in acron 4.x

**Comment by twada** [comment]
@dead-horse Thank you!

Would you use annual version `2017` instead of `8` for [ecmaVersion](https://github.com/ternjs/acorn#main-parser)?

Failing tests are due to the changes in embedded recorder. It's not your fault. My bad 😞

**Comment by dead-horse** [comment]
@twada fixed, thanks for your quick response and fantastic work!

**Comment by twada** [comment]
@dead-horse Thanks again. I'll merge this, fix failing tests, then release ASAP.

**Comment by twada** [comment]
Just released as [version 2.0.1](https://github.com/power-assert-js/espower-source/blob/master/CHANGELOG.md#201-2017-02-13). Thanks @dead-horse !

**Pull request merged**
